spring.datasource.url: jdbc:mysql://localhost:3306/search_engine
spring.datasource.username: tester
spring.datasource.password: testtest1
spring.jpa.hibernate.ddl-auto: update
#spring.jpa.properties.hibernate.format_sql: true
#logging.level.org.hibernate.SQL: DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
sites:
  - url: http://www.playback.ru
    name: playback.ru
  - url: https://volochek.life
    name: volochek.life
  - url: http://radiomv.ru
    name: radiomv.ru
  - url: https://ipfran.ru
    name: ipfran
  - url: https://dimonvideo.ru
    name: dimonvideo
  - url: https://nikoartgallery.com
    name: nikoartgallery
  - url: https://et-cetera.ru/mobile
    name: et-cetera.ru
  - url: https://www.lutherancathedral.ru
    name: lutherancathedral.ru
  - url: https://dombulgakova.ru
    name: dombulgakova
  - url: https://www.svetlovka.ru
    name: svetlovka.ru
fields:
  - name: title
    weight: 1.0
  - name: body
    weight: 0.8
user-agent: Scouser122
web-interface-path: /admin
backend-api-url: http://localhost:8080